### ISSUE TITLE
Little typo on K-theory notes?

### ISSUE THREAD

**Issue by solov-t** [FlorianAdler/AlgebraBonn#4]
Hello Florian,

On the K-theory notes, example I.15 (e) is it supposed to be tensor product over $R$? And also on the definition of C^simp, etc, etc... I think Fabian said over Z as well, but I'm a bit confused.

(Great notes btw!)

**Comment by solov-t** [comment]
Also I think Fabian used a normalized version of C^simp, which maybe is worth pointing out but idk.

**Comment by FlorianAdler** [comment]
Thanks for the feedback!

I'm pretty sure the tensor product should be taken over Z because C^simp, as we defined it, has coefficients in Z and is thus not an R-module. But you could also define C^simp with coefficients in R instead of Z, and then the tensor product should indeed be taken over R (and $C\otimes_Z C^simp(X)$ is the same complex as $C\otimes_RC^simp(X,R)$).

However, you are totally right about that C^simp should be normalized (I somehow forgot that $\Delta^n$ contains degenerate simplices lol) and I believe Dold-Kan only works that way.

I'll try to fix this together with tomorrow's lecture, but I'll still keep the issue as there will undoubtedly be more errors like this.

**Comment by solov-t** [comment]
Oh yes this makes perfect sense! Somehow I was tired and didn't try to actually compute this haha
