### ISSUE TITLE
complex oriented

### ISSUE THREAD

**Issue by brankoju** [FlorianAdler/AlgebraBonn#7]
Just a small issue on page 175… you use KU instead of ku because you were concerned whether $ku$ is complex oriented. It should be complex oriented because the homotopy groups vanish in odd degrees, see e.g. lurie's lecture notes on chromatic homotopoy theory, lecture 4, remark 4 (one could also use remark 3 and that ku  is the connective cover of KU ) 

I was a bit confused why we actually obtain `ku^0(ku)=KU^0(ku)` in the end. The reason is a sign error  (which also appears in Lurie's lecture notes... or he has different conventions). I think that `E^*(BU(n)) \simeq \pi_{-*}(E)[[c_1, \dots , c_n]]`  . In particular  `E^*(BU(n))`   should be a module over  `\pi_{-*}(E)` (and not `\pi_*(E)`) because a class in  `E^k(BU(n))`   is represented by a map   `S[-k] \to E` in spectra (and not  `S[k] \to E` )

**Comment by FlorianAdler** [comment]
You're absolutely right. Fabian also sent me an e-mail about this error and he confirmed that Lurie's lecture notes have a weird sign convention. Which is never mentioned :angry:. Misunderstanding Lurie's sign convention is also what made me think `ku` should not be complex oriented (because as you said, we wouldn't obtain `ku^0(ku)=KU^0(ku)`). 

I've fixed this in the latest version, which went online a few minutes ago.
